CREATE DATABASE `153671-yeticave`
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
USE `153671-yeticave`;

CREATE TABLE categories (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` CHAR(128) NOT NULL
);

CREATE TABLE lots (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(128) NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `description` TEXT DEFAULT NULL,
  `img_path` CHAR(128) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `bets_step` INT UNSIGNED NOT NULL,
  `start_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `end_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `author_id` INT UNSIGNED DEFAULT NULL,
  `winner_id` INT UNSIGNED DEFAULT NULL
);

CREATE TABLE bets (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `price` INT UNSIGNED NOT NULL,
  `author_id` INT UNSIGNED NOT NULL,
  `lot_id` INT UNSIGNED NOT NULL
);

CREATE TABLE users (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `email` CHAR(128) NOT NULL UNIQUE NOT NULL,
  `name` CHAR(128) NOT NULL,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `password` CHAR(128) NOT NULL,
  `avatar_path` CHAR(128) DEFAULT NULL,
  `contact_info` CHAR(255) DEFAULT NULL
);